### ISSUE TITLE
when you release the code?

### ISSUE THREAD

**Issue by barshag** [vis-nlp/ChartInstruct#1]

**Comment by AhmedMasryKU** [comment]
The code and models will be ready in the next few weeks. Sorry, but we were quite busy with the ACL review process and rebuttal.

**Comment by Ryoo72** [comment]
I am also waiting :)

**Comment by AhmedMasryKU** [comment]
Hey Guys, sorry for keeping you waiting. 
The model, inference code, and finetuning code are now publicly available! 
I also made a nice web demo to try the model on huggingface.
